version: 2
jobs:
  build:
    commit:
    acceptance:
    manual_test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "Hello World"
workflows:
  version: 2
  deplayment_pipeline: #workflowtest
  jobs:
    - commit
    - acceptance:
        requires: #
          -commit
    - manual_test:
        requires: #
          -acceptance
    - release:
        requires: #
          -manual_test
