version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-31
    steps:
      - checkout
      - run: #
        - name: Download Dependencies
        - command: ./gradlew androidDependencies
      - run:
        - name: Run Compile
        - command: ./gradlew assembleDebug
