version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run: # a
         name: Download Dependencies
         command: ./gradlew androidDependencies
      - run: # b
         name: Run Compile
         command: ./gradlew assembleDebug
